apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.application.name }}
  namespace: {{ .Values.application.namespace}}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.application.name }}
  ports:
    - name: test-app
      nodePort: {{ .Values.service.nodePort }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}